version: "3.9"
services:
    web:
      build: .
      ports:
        - "80:3000"
      entrypoint: ["npm", "run", "dev"]
      volumes:
        - .:/src/app/
    mongo:
      image: mongo
      restart: always
      volumes:
        - ./mongo/data:/data/db
